### ISSUE TITLE
Why redirect method on Plug.Conn in Maru would change the request method to "GET"

### ISSUE THREAD

**Issue by TIZ36** [falood/maru#128]

**Comment by lianhj** [comment]
in response.ex line 30 function redirect, limit the code in [301, 302], it will change your post method to get, change code to 307 works for me. I think the code should be a param in options, so we can customize
![image](https://user-images.githubusercontent.com/24893624/121146437-8057d980-c872-11eb-9ae9-568e7872fdb9.png)
