### ISSUE TITLE
Pass param options as second argument to ParamType

### ISSUE THREAD

**Issue by venkatd** [falood/maru#21]
Right now I implement a param type like so:

```elixir
defmodule Maru.ParamType.Time do
  def from(string) do
    case Timex.parse(string, "{ISO:Extended}") do
      {:ok, time} ->
        time
      {:error, _} ->
        raise Turtle.API.InvalidParamException, error: "Invalid time #{string}. Expected ISO8601 like 2016-04-21T22:26:01Z"
    end
  end
end
```

Two things
- I would like to control the format like `requires :time, allowed_formats: ["m/d/Y"]`.
- I would like to specify the field that is invalid so I can provide more friendly errors. For example I could print `The start_time parameter was an invalid time.`

I think if the 2nd argument got all of the options it would solve this.

What do you think of this? Thanks!

**Comment by falood** [comment]
As our last talk via #20, the second point is OK.
But I can't get your point about `second argument`. What do you define `allow_formats: ["m/d/Y"]` for? Could you show me more details or examples?

**Comment by falood** [comment]
This feature has been achieved at master version, and [here](https://maru.readme.io/v0.10/docs/params#section-custom-parameter-type) is the document.
Will this resolve your problem? Feel free to give me any suggestion, please.

**Comment by venkatd** [comment]
Thanks @falood this will do the trick. I will upgrade and get back to you with any suggestions.

**Comment by falood** [comment]
maru v0.10.0 is out :D
