### ISSUE TITLE
support desc block

### ISSUE THREAD

**Issue by AndwareSsj** [falood/maru#22]
like this:
desc 'Returns your public timeline.' do
  detail 'more details'
  params  API::Entities::Status.documentation
  success API::Entities::Entity
  failure [[401, 'Unauthorized', 'Entities::Error']]
  named 'My named route'
  headers XAuthToken: {
            description: 'Valdates your identity',
            required: true
          },
          XOptionalHeader: {
            description: 'Not really needed',
            required: false
          }

end
?? ruby grape

**Comment by falood** [comment]
That's a good idea but I have to bump next release first.
I almost rewrite maru via master version, And I must make sure it's usable and stable first.
