### ISSUE TITLE
Test: make_response should not require a version 

### ISSUE THREAD

**Issue by dblock** [falood/maru#24]
If you don't supply a version to `make_response` below (remove `"v1"`)

```elixir
    test "/" do
      assert %Plug.Conn {
        resp_body: "It works! port: 8800"
      } = conn(:get, "/") |> make_response("v1")
    end
```

you get

```
  1) test / (EchoServerTest)
     test/echo_server_test.exs:5
     ** (UndefinedFunctionError) undefined function EchoServer.__version__/0
     stacktrace:
       (echo_server) EchoServer.__version__()
       EchoServerTest.make_response/2
       test/echo_server_test.exs:6
```

Seems odd.

**Comment by falood** [comment]
It seems that these code is copied from [maru_examples](https://github.com/falood/maru_examples).
The master version is totally rewrote version which is not forward compatible.
I do not update `maru_examples` yet and I'll do it soon.

**Comment by falood** [comment]
I have update `maru_examples` for maru v0.10.0

**Comment by dblock** [comment]
I get it now, thanks!
