### ISSUE TITLE
Online documentation link (on Hex.pm) does not work

### ISSUE THREAD

**Issue by Qqwy** [falood/maru#27]
Maru seems like an interesting project. However, the link   to the documentation ( https://hexdocs.pm/maru/ ) that is linked to from both the Hex.PM page as well as the Guides website, does not work.

You are redirected to https://hexdocs.pm/maru/extra-readme.html , which returns a 404 status code.

**Comment by falood** [comment]
Thank you :D 
It should be redirected to [https://hexdocs.pm/maru/readme.html](https://hexdocs.pm/maru/readme.html) and it's fixed now.
Also see [https://maru.readme.io](https://maru.readme.io).
If you're using the master version, [https://maru.readme.io/v0.10](https://maru.readme.io/v0.10) is helpful.
I'll release v0.10.0 these days, it's quite different with v0.9. So master version is recommended.
