### ISSUE TITLE
Request params map permissiveness

### ISSUE THREAD

**Issue by ckampfe** [falood/maru#3]
Grape seems to allow request parameters to pass through to the `params` object that are not named in the `params` block.

Maru seems to take the other opinion, not placing request parameters in the `params` map that are not named in the `params` block.

Is there any way to have Maru allow all extra params into the `params` map while still enforcing the `requires` and `optional` constructs, a la Grape? I have it in my head as something like an atom passed to the params macro, maybe something like:
 
```elixir
params :lenient do
   # constraints here
end
```

I'm open to trying to hack this myself, but this is my first experience with Elixir (it's really cool!), so I'm not sure really where to start ([I'm guessing here](https://github.com/falood/maru/blob/54c1c0c2f4cdda05ca0ec16a3e1f3e3fa7c79a26/lib/maru/builder/params.ex)).

Just curious if something like this is either possible or wanted. Thanks for your work, Maru is great!

**Comment by falood** [comment]
Thanks for pointing it out. I will check grape's implementation and fix it.

**Comment by falood** [comment]
I'm sorry it's difficult to do a integrated copy.
The variable `conn.params` is a `Map` which has `String` type keys and I don't think convert it to `atom-keys-map` is a good idea.
Erlang VM has restrictions on the number of `Atom`, so convert uncertain string by `String.to_atom` is evil.
