### ISSUE TITLE
List parameters

### ISSUE THREAD

**Issue by ulfurinn** [falood/maru#31]
I cannot for the life of me figure out how to declare a parameter that is a list of primitives.
Looking at the sample in the guide:

```
  optional :preferences, type: List do
    requires :key
    requires :value
  end
```

this will declare a list of maps with "key" and "value", won't it?
What if I want a list of integers?

**Comment by Cifer-Y** [comment]
```
 optional :preferences, type: List do
    requires :key
    requires :value
  end
```

above code means:
` params[:preferences] = [%{key: 1, value: 1}, %{key: 2, value: 2}]`

If you just want a list of integers, I usually do as follow:

1. in params declaration: `requres :my_int_list, type: String

2. and in your request you can post a json like:  `{"my_int_list": "1,2,3,4,5"}`
3. then in the endpoint, you can get a list of integers `[1,2,3,4,5]` by
    `params[:my_int_list] |> String.split(",") |> Enum.map(&String.to_integer/1)`

Or you can do that converting by using a custom maru type.

@ulfurinn Hope to be able to help you.

**Comment by falood** [comment]
@ulfurinn The explanation of `List` type by @Cifer-Y is completely correct.
But there's no need to parse params within endpoint block.
[pipe types](https://maru.readme.io/docs/params#section-pipe-types) is helpful.
if you post a json like `{"my_int_list": "1,2,3,4,5"}`, you can get `{my_int_list: [1, 2, 3, 4, 5]}` by 
```elixir
requires :my_int_list, type: fn s -> s |> String.split(",") |> Enum.map(&String.to_integer/1) end
```
And you can [custom your own type](https://maru.readme.io/docs/params#section-custom-parameter-type) to parse it if you use it continually.

I'm going to add a DSL like `type: List[Integer]` to make is easy to parse non-nested list. It's on the way.

**Comment by ulfurinn** [comment]
Forcing everything into a string is not an acceptable solution.

> I'm going to add a DSL like type: List[Integer] to make is easy to parse non-nested list. It's on the way.

This would be great, provided that the swagger generator can also handle it correctly.

**Comment by falood** [comment]
I see. Thank you.

**Comment by falood** [comment]
I think this issue should be closed, maru swagger support one line list now. https://github.com/falood/maru_swagger/commit/c18e08c3f685df8d539821aeb0f86d891739b3c8
