### ISSUE TITLE
Some basic performance benchmarks / notes would be nice

### ISSUE THREAD

**Issue by Trevoke** [falood/maru#32]
One of the main reasons to bring in Elixir nowadays, for better or for worse is "vs. Ruby" or "vs. Scala", so benchmarks are a useful thing to point at.

It would be nice to have some performance benchmarks for maru!

**Comment by falood** [comment]
Yeah, I'll do it later.
Thank you.

**Comment by falood** [comment]
@Trevoke
I don't think it's necessary to compare with other language, so I created [benchmark](https://github.com/falood/benchmark) to compare frameworks based erlang VM.
It's under development.

BTW, [this](https://github.com/mroth/phoenix-showdown) repo may interest you.

**Comment by Trevoke** [comment]
It did. I went there first. They didn't want to add maru.

https://github.com/mroth/phoenix-showdown/issues/32

**Comment by Trevoke** [comment]
For people trying to convince a company to move to an Erlang-based language, a benchmark comparing other languages is useful :)

**Comment by falood** [comment]
Phoenix showdown stop adding any more new frameworks, so I have to do it myself.
I think benchmarks by techempower is enough to compare between languages and I'm not good at ruby or scala, so I'll force on EVM based frameworks.
Maru base on plug and plug base on cowboy, I think the performance attrition rate is important.

**Comment by Trevoke** [comment]
That's true. It may just mean we need another project that brings together some of these disparate benchmarks.
