### ISSUE TITLE
How to run a maru app without `iex`?

### ISSUE THREAD

**Issue by aisrael** [falood/maru#37]
All the documentation I've read goes `iex -S mix`.

If I just type `mix` it displays `Running Elixir.MyAPP.API with Cowboy on http://127.0.0.1:8880` then promptly exits.

What if I'm eyeing to deploy this to production, do I really need to have an interactive app waiting for input?

**Comment by Kabie** [comment]
You can run it with `mix run --no-halt`. Or deploy it with [distillery](https://github.com/bitwalker/distillery).

**Comment by aisrael** [comment]
Thanks. Is that something that should be in the docs, or is it something that should be common knowledge in #elixir?

**Comment by Kabie** [comment]
Just do `mix help` and `mix help run`, you will find the usage.
