### ISSUE TITLE
Maru ignores input parameter if its value is null

### ISSUE THREAD

**Issue by take-five** [falood/maru#41]
Hello!

I wanted to give Elixir a try and tried to implement very simple JSON API using Maru. Maru is looking good for me at the moment, but I've found strange behavior recently.

Here is Maru router which describes what I've found:
```elixir
defmodule API do
  before do
    plug Plug.Parsers,
      pass: ["*/*"],
      json_decoder: Poison,
      parsers: [:urlencoded, :json, :multipart]
  end

  params do
    optional :phone, type: String
  end
  post do
    conn |> json(params)
  end
end
```

I expect that this endpoint will return a JSON containing exact value of given `phone` param.
It works in most cases:
```
$ curl -H "Content-Type: application/json" -X POST -d '{"phone":"123"}' http://localhost:4000/
{"phone":"123"}
```

But if I pass "null" value, `maru` will discard this parameter completely:
```
$ curl -H "Content-Type: application/json" -X POST -d '{"phone":null}' http://localhost:4000/
{}
```

This behaviour restricts JSON API very much, so as an API designer I can't provide ability to use `null` values for certain keys (which is necessary in my case).

Is this intentional or is it a bug? Thanks :)

**Comment by falood** [comment]
Hi @take-five , This is intentional. 
It's suitable in my case and I followed this guide [Null_Property_Values](https://google.github.io/styleguide/jsoncstyleguide.xml#Empty/Null_Property_Values).
Could you please show me your case used it?

**Comment by take-five** [comment]
I'm designing a simple REST API which supports CRUD operations. Let's say, I want to update user information via REST API. "phone" column can have `null` values, it's a legacy DB and I can't change. So how do I set "phone" to `null` via REST API? I can pass empty string, but that's very confusing for API user.

**Comment by take-five** [comment]
Also, I guess Google guide refers mostly to JSON response rather than request

**Comment by falood** [comment]
how about decide whether keep it by an option like this: 
when I pass `{"phone": null}` to endpoint, `optional :phone, keep_blank: true` will got `%{phone: nil}`
and `optional :phone` will got `%{}` ?

**Comment by take-five** [comment]
Sounds like a good plan. Will `optional :phone, keep_blank: true` implicitly set parameter to `nil` if it wasn't passed? I believe it shouldn't.

**Comment by falood** [comment]
Of cause, it shouldn't.
