### ISSUE TITLE
Add documentation / example for lists.

### ISSUE THREAD

**Issue by idyll** [falood/maru#43]
It would be great if the documentation included an example like:

```
params do
  requires :tags, List[String]
end
```

as I had to do a bit of code spelunking to figure out how to allow for a list of strings.

**Comment by falood** [comment]
Hi @idyll 

I have update it [here](https://maru.readme.io/v0.10/docs/params#section-one-line-list-params) and you can check [test case](https://github.com/falood/maru/blob/89f048e4554bf0dab8b2f6a179a6e3cd50341927/test/builder/route_test.exs#L146-L170) for simple usage.

Leave me a message if you have any other questions, please.

**Comment by idyll** [comment]
Awesome. Thanks.
