### ISSUE TITLE
Incoherance in the get started doc

### ISSUE THREAD

**Issue by alexjp** [falood/maru#9]
Hi,

Sorry this is really nitpicking but in the get started webpage, you mention:
```
config :maru, MyAPP.API,
    http: [port: 8880]
```
and then
```
$ curl 127.0.0.1:4000
{"hello":"world"}
```

which should be 8880 ( or change config to 4000 ).

!! sorry for nitpicking !!

**Comment by Cifer-Y** [comment]
Yeah, typo again :smile_cat:

**Comment by falood** [comment]
Thank you!
Fixed!
